spring.application.name=UBER-BACKEND-PROJECT

# ===============================
# = DATABASE CONFIGURATION (Docker)
# ===============================
spring.datasource.url=jdbc:postgresql://db:5432/uberdb
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update               
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# = SECURITY CONFIG (JWT)
# ===============================
jwt.secretKey=asdfasdfasdfasdtqerg345345tgfdhw4ertgw4ertgwerfdshw45ertgbgfdtq43rehbtrdtgrfb

# ===============================
# = MAIL CONFIGURATIONS (Gmail SMTP)
# ===============================
spring.mail.username=${DATABASE_GMAIL}
spring.mail.password=${DATABASE_GMAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
