spring.application.name=UBER-BACKEND-PROJECT

# database configurations
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true

#security config
jwt.secretKey =${JWT_SECRETKEY} 

# mail configurations
spring.mail.username=${DATABASE_GMAIL}
spring.mail.password=${DATABASE_GMAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


